### ISSUE TITLE
Question: two transfers with the same value

### ISSUE THREAD

**Issue by akolotov** [atvanguard/ethsingapore-zk-dai#1]
Could you clarify the current implementation of `Note`? If we look at the method `claimNote`, it seams that `Note` is associated with an address (_pk_) and a value and this address cannot have another note with the same value.
https://github.com/atvanguard/ethsingapore-zk-dai/blob/4955d5f8fad5a0c973353458455b0994a0461786/ethereum/contracts/SecretNote.sol#L22

In other words is it assumed that there is no two transfers for the same recipient with the same value?

Is this to force users to use different addresses to get transfers?

**Comment by arminvoid** [comment]
Hi @akolotov 
The notes will also have a third-param which is a random nonce. So a note will be `Hash(owner, value, nonce)`. This implementation was only for a 36-hour hackathon, hence we skipped it - sorry about that. If you are interested you can take a look at the new [design doc](https://docs.google.com/document/d/1z3ZRLLD-wvgERe_KO5VhqxEJDqiBd3xxfLO1pYk7Z0k/edit).

Feel free to re-open the issue if you have any further questions.
